include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - doc/**
    - build/**
    - android/**
    - windows/**

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
